micronaut:
  application:
    name: micronautUam
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/micronaut-uam
    username: micronaut-uam
    password: "micronaut-uam"
    driverClassName: org.postgresql.Driver
    db-type: postgresql
    dialect: POSTGRES
netty:
  default:
    allocator:
      max-order: 3
flyway:
  datasources:
    default:
      enabled: true
